= Backup and Restore

Backups are snapshots of the state of your solutions at a given point in time. Currently, any paid solutions provisioned by an account with a valid payment method can have a maximum of 7 concurrent backups.

[NOTE]
====
The backup feature is not supported on free-tier instances or instances provisioned by an account without a valid payment method.
====

All tasks described on this page can be completed in the *Admin Portal*. To get to the *Admin Portal*, go to the *My Solutions* page in GraphStudio and click *Admin* in the upper-right corner.

image::image (66).png[]

== Data Storage and Encryption

Backups are saved to Amazon EFS on AWS, Azure Files on Microsoft Azure, and GCP Filestore on GCP. Backup storage is provisioned when you start a paid-tier solution and is based on the maximum number of backups allowed (currently fixed at 7). It only stops incurring charges when the solution is terminated. Stopping the solution does not stop charges for backup storage.

Backups are encrypted by default using the native encryption feature of the cloud provider with platform-managed keys.

== Scheduled backup

By default, scheduled backup is turned on when instances are running and will be done daily. If the maximum retention number is reached when a new backup is made, the oldest scheduled backup will be deleted. The backup schedule can be customized.

=== Change backup schedule

==== 1. Click Backup & Restore.

On the left side of the screen, click *Backup & Restore.*

==== 2. Specify backup schedule.

Choose the backup frequency you want and supply the password of your TigerGraph user.

image::image (26).png[]

==== 3. Click UPDATE.

== Manual backup

Aside from scheduled backups, you can also make backups manually in the  Admin Portal.

[NOTE]
====

* If you want to perform a manual backup when there are already seven copies of backups, you must delete an older backup.
* The maximum number of manual backups is six, as the platform always reserves one spot for scheduled backups.
====

Below are the procedures to create a backup manually in the Admin Portal.

[discrete]
==== 1. Click Backup & Restore.

[discrete]
==== 2. Provide tag and password.

In Backup/Restore, supply a tag for your backup and enter the password of your TigerGraph user.

image::image (56).png[]

[discrete]
==== 3. Click BACK UP.

== Restore a backup

You can use a backup to restore your solution.

Below are the procedures to restore a backup in the Admin Portal:

==== 1. Click Backup & Restore.

[discrete]
==== 2. Copy backup tag.

In *Manage Backups*, find the backup you want to use for the restore and click the clipboard icon to copy the tag of the backup.

image::image (48) (2).png[]

== Delete a backup

Below are the procedures to delete a backup in the Admin Portal.

[discrete]
==== 1. Click Backup & Restore.

[discrete]
==== 2. Go to Manage Backups.

[discrete]
==== 3. Delete the backup.

In the Backup List, find the backup you want to delete and click the delete button in the *Action* column.

image::image (48) (1).png[]
