= Private Access Services

TigerGraph offers private access services through AWS (AWS PrivateLink), Azure (Azure Private Link), and GCP (Private Service Connect).

This section includes instructions on setting up private access through TigerGraph Cloud Classic.

This feature is only available to new clusters on regions that support private endpoints, not clusters existing before the feature release.
If your cluster was active before this feature was released in June 2022, you cannot create a private link in that region. Please contact TigerGraph support for information about upgrading to be able to create private links.

Private access services are only available for paid clusters.

== Setup overview

. Create a new cluster on TigerGraph Cloud Classic.

. Choose "Private" or "Public" for the "TigerGraph Endpoint Type".

. Connect the new cluster to your account with the cloud provider.

See each cluster's main page for a detailed guide.

* xref:private-access/gcp.adoc[]

* xref:private-access/aws.adoc[]

* xref:private-access/azure.adoc[]