= Amazon Web Services (AWS)

== Regions

* US-West-1 (Northern California, USA)
* US-East-1 (Northern Virginia, USA)
* US-East-2 (Ohio, USA)
* EU-West-1 (Dublin, Ireland)
* EU-West-2 (London, UK)
* EU-Central-1 (Frankfurt, Germany)
* AP-Northeast-1 (Tokyo, Japan)
* AP-Southeast-1 (Singapore)
* AP-Southeast-2 (Sydney, Australia)
* AP-Southeast-3 (Jakarta, Indonesia)
* SA-East-1 (São Paulo, Brazil)

== Instance types

The table below shows the instance types available on AWS.

|===
| Instance name | vCPU | RAM (GiB)

| TG.Free
| 4
| 7.5

| TG.C4.M16
| 4
| 16

| TG.C8.M15
| 8
| 15

| TG.C8.M32
| 8
| 32

| TG.C16.M64
| 16
| 64

| TG.C16.M122
| 16
| 122

| TG.C16.M128
| 16
| 128

| TG.C32.M244
| 32
| 244

| TG.C32.M256
| 32
| 256

| TG.C64.M488
| 64
| 488

| TG.C64.M512
| 64
| 512

| TG.C96.M768
| 96
| 768
|===

== Disk storage

On AWS, disk storage refers to the https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volumes.html[EBS volume] attached to your TigerGraph Cloud Classic instance. By default, data in disk storage is encrypted-at-rest with platform-managed keys.

Disk storage is charged per GB per hour.

== Backup storage

Cluster backups on AWS are stored on https://aws.amazon.com/efs/[Amazon Elastic File System] (EFS) and automatically encrypted at rest with platform-managed keys. When a cluster is provisioned, backup storage is part of the running cost of the cluster and only stops incurring charges when the cluster is terminated.

Backup storage is charged per GB per hour.
