= IDP integration with SSO

////
By default, user management in a TigerGraph Cloud organization happens in the xref:manage-org-users.adoc[] section of the TigerGraph Cloud interface.

If you have another preferred identity provider (IDP), you can integrate with it instead using SAML 2.0 to handle your user management needs outside of TigerGraph Cloud.
////

IDP integration is currently available at the Organization level, so one IDP will handle user management for all clusters in that organization.
Only one IDP can be connected to a single Organization.

== Process Outline

. Have IDP enabled on your TigerGraph Cloud Organization account.
. Create an app integration on the IDP side to configure it to link with TigerGraph Cloud.
. Users log in to the TigerGraph Cloud portal using credentials from your IDP.
. Organization Admins assign roles to the users being created in the cloud organization via successful login from the IDP.

== Setup

This process is currently done through TigerGraph support.
Please contact beta-support@tigergraph.com to reach out to a technical support engineer who will guide you through the process.

