= Glossary

== backup

A snapshot of the state of your clusters at a given point in time.

== cluster

A fully-managed TigerGraph instance or a group of instances connected together. TigerGraph allows High Availability (HA) clusters that provide redundancy so that user instances are not interrupted in the case of a server outage.

== credentials

Information authenticating a user's identity. TigerGraph allows either username:password or API token credentials.

== GraphStudio

TigerGraph's visual interface for designing a graph, ingesting data, exploring the graph, developing and running queries, and visualizing the results.

== GSQL

TigerGraph's query language for fast and scalable graph operations and analytics.

== instance

One virtual machine or virtual server.


== partitioning factor

An internal TigerGraph characteristic of a TigerGraph cluster that determines how the data in the database will be distributed

== read-only workspace

A workspace where only read operations are allowed. It is optimized for read-intensive operations.

== read-write workspace

A workspace that allows read and write operations on the graph data.

== replication factor

A characteristic of the cluster design that will determine the number of copies of data that will be stored in the cluster.

== resizing

Allocating more or fewer resources to existing instances, enabling a balance between cost and performance as workloads change.

== REST++/RESTPP

A REST server customized for TigerGraph users.

== role-based access control

A policy-neutral access-control mechanism defined around roles and privileges.

== schema

A formal description of a graph's data model.

== solution

The previous name for a cluster, or a fully-managed TigerGraph deployment.


== TigerGraph user

A database user with its own roles and privileges for different graphs stored on a cluster.

== vCPU

A virtual central processing unit. A vCPU is a core within a virtual machine inside TigerGraph Cloud.

== VPC

Virtual Private Cloud. A private cloud environment inside a public cloud. By default, your instances are separated from other TigerGraph users by different VPCs. The term "VPC" is used by AWS and GCP, while Azure uses "VN" for "Virtual Network."

== VPC Peering

A network between two VPCs allowing instances to communicate as if they are on the same network.

== web shell

A browser-accessible command line for running GSQL commands on a TigerGraph Cloud cluster.

== workgroup

A workgroup represents a project or a logical group within TigerGraph Cloud. It serves as a container that holds multiple workspaces and databases related to a specific use case, team, or application.

== workspace

A workspace is a compute unit within a TigerGraph database.

//== data topology size

//data topology size check

//Workgroup

//Workspace


