= Release Notes
:page-toclevels: 1
:page-aliases: release-notes.adoc

New updates to TigerGraph Cloud, both to the user experience and the backend capability, are regularly released.
This page provides a summary of each update upon release.

These TigerGraph Cloud updates are separate from updates to the core TigerGraph architecture. For release notes about new TigerGraph versions, see xref:tigergraph-server:release-notes:index.adoc[TigerGraph Server Release Notes].

Cloud clusters are not automatically upgraded to a new TigerGraph version when a new version is released.
For version upgrades for existing clusters, please contact TigerGraph Support.

== April 19, 2023 Update

== February 28, 2023 Update

TigerGraph 3.9.0 available

== February 17, 2023 Update

=== Feature Updates

* Redesigned Create Cluster page, making it much easier for users to see and choose what services they would like.
* Introduction of Professional Tier and Enterprise Tier offerings.
* Introduction of the ML Bundle, so users can select the TigerGraph DB plus the Machine Learning Workbench on a starter-size VM with just one click.
* Faster cluster management operations for the Free Tier:
** Creating a cluster is 5x faster than before, not only 2 minutes.
** Pausing, resuming and terminating a cluster is 5x faster than before, now less than 1 minute.

== January 2023 Updates
Release date: January 18th, 2023

=== Feature updates
* Invoices are now sent in PDF format.
* Disks on AWS can now be resized up to 2TB.

=== Fixed issues

* Disk resize limits now match the limits from each cloud service provider.

=== Known issues
* Subscriptions to TigerGraph Cloud from cloud service provider marketplaces occasionally encounter issues during setup.
Please contact TigerGraph Support for assistance if your account is affected.

== November 2022 Updates

Release date: November 15th, 2022

=== Feature updates

* xref:insights:intro:index.adoc[TigerGraph Insights,] an all-new data visualization platform, is now available in TigerGraph Cloud
* xref:ml-workbench:on-cloud:on-tgcloud.adoc[Machine Learning Workbench] is now integrated seamlessly into TigerGraph Cloud
* Added a dedicated starter kit for Machine Learning Workbench on TigerGraph Cloud
* Reworked Billing and Analytics pages for improved ease of use
* TigerGraph 3.8.0 is now available when creating new clusters

---

Release date: November 9th, 2022

=== Feature updates
* Updates to service termination flow: Paid tier cluster will not be automatically terminated
* Removed $25 free credit for new users
* Added Jakarta (Indonesia) region to AW.
* Added Arizona (US) and Washington (US) regions to Azure
* Re-organized starter kits into new categories
* Added user and organization xref:solutions:monitor-cluster-activity.adoc[Activity Logging]

=== Fixed issues

* Fixed an issue where customers with outstanding balances were unable to create free-tier clusters.
* Fixed an issue with creating a user named `tigergraph` as a database user.

== October 2022 Updates

Release date: October 12th, 2022

=== Feature updates

* Overhauled Create Cluster workflow to greatly streamline the user experience.
** Users can now create new clusters on a single page and apply default settings with one click.

---

Release date: October 5th, 2022

=== Feature updates
* Clarified in new user email that each new user invitation will only last seven days and must be resent if not accepted within that time
* Backend improvements reducing cluster provisioning time
* Security enhancements

=== Fixed issues

* Fixed an issue where some clusters were created with attributes set as empty strings instead of null values, which could have caused API problems in rare cases.
* Fixed an issue with the GCP filestore in cases where cluster provisioning failed.
//* Fixed an issue where leaving a browser window with a Cloud instance open and idle for several hours would raise a "Refused to connect" error.

== September 2022 Updates
Release date: September 15th, 2022

=== New Features
* Enabled SSO with Okta and Azure Active Directory
* Seamless UI redesign that integrates with the TigerGraph Suite of web applications
* TigerGraph 3.7.0 is available when creating new clusters

=== Feature updates
* UI refinements with a focus on intuitive use
* Shift in terminology from "Solution" to "Cluster"

=== Known issues

* In rare cases, leaving a browser window with a Cloud instance open and idle for several hours will raise a "Refused to connect" error.
Log out and log in again to fix this error.

== August 2022 Updates
Release date: August 18th, 2022

=== New Features
* Users with an invitation can provision xref:ml-workbench:on-cloud:mlwb-service.adoc[ML Workbench (preview version)] instances on top of TigerGraph Cloud clusters.
** If you are interested in experimenting with ML Workbench on TigerGraph Cloud, please contact sales@tigergraph.com
* TigerGraph 3.6.2 is available when creating new clusters.

=== Feature updates
* Organization Admins can now create username-password pairs for user authentication from TigerGraph connectors and the remote GSQL client.
* Minor UI improvements.

== July 2022 Updates

Release date: July 6, 2022

=== New Features

* Multiple users can now share access to the same organization account.
* Role based access control (RBAC) to control and manage access to specific clusters and capabilities.
* TigerGraph Cloud Console and GraphStudio user authentication are now integrated to eliminate repeated logins.
* All-new clean and unified user interface.

=== Feature Updates

* Username/password authentication has changed for connectors to TigerGraph Cloud instances.
** Users need to create a secret in the Admin Portal UI.
** Secrets can only be created through the GUI after a graph has been created.
** When entering the credentials, the username needs to be `\__GSQL__secret`, and the password needs to be the secret.

== June 2022 Updates
Release date: June 20, 2022

=== New features

* TigerGraph Version 3.6.0 is now available for selection when creating new clusters.
* xref:security:private-access/index.adoc[Private Link connections] can now be created for TigerGraph clusters for secure, private access.
** Private Links are supported across all cloud providers: AWS, Azure, and GCP.
** Clusters can have public or private access.

=== Feature updates

* TigerGraph Cloud clusters created on or after June 20, 2022 no longer expose ports 14240 or 9000.
This also applies to previously created clusters that are resized on or after June 20, 2022. Use port 443 instead for API endpoint connectivity:
** Use API endpoint `443/restpp/<endpoint>` for RESTPP endpoints that were on port 9000
** Use API endpoint `443/<endpoint>` for endpoints that were on port 14240
* Resizing a cluster created before June 20, 2022 will cause data loss due to a backend improvement in cluster resizing.
Always back up a cluster before performing a resize operation.

=== Known issues

* The GSQL Web Shell is temporarily disabled for new clusters due to recent networking improvements on the TigerGraph Cloud backend. Clusters created before June 20, 2022 are unaffected and still have access to the Web Shell.

** Use the xref:tigergraph-server:gsql-shell:using-a-remote-gsql-client.adoc[Remote GSQL client] to access GSQL on new TigerGraph Cloud clusters until access is restored.


== May 2022 Updates
Release date: May 12, 2022

=== New features

* TigerGraph Version 3.5.3 is now available for selection when creating new clusters.
* *Free-tier clusters on Azure.* We now offer the option to create a free-tier cluster on Azure along with Amazon Web Services (AWS) and Google Cloud Platform (GCP).
* Enabled search by cluster ID in cluster list.
* Added download button for cluster management.


=== Feature updates

* *Netdata deprecation*. Monitoring network I/O data through Netdata is no longer supported because of security vulnerabilities.
* Removed dependencies between credit card and backups when there are credits on account.
* User interface improvements for quota outages
* Improved observability with tags now on cluster information
* GSQL Output Path restricted for increased file security.

== Feb 2022 Updates
Release date: Feb 8th, 2022

=== New features

* TigerGraph Version 3.5 is now available for selection when creating new clusters.
* Added the framework to render TigerGraph Cloud UIs in other languages besides English.
* Improvements on secure access and auditability.
* Improvements on operational SLAs and faster resolution of issues.

== Sep 2021 Updates

Release date: Sep 22, 2021

=== New features

* **TigerGraph V3.1.5 is now available for selection when creating new clusters**. Users can create clusters that include both single server and cluster deployment when they choose TigerGraph V3.1.5.
* *VPC Peering*. Users can now create a VPC peering connection between their TigerGraph Cloud VPC and another VPC on all supported cloud providers.
* *Automatic load balancing for HA clusters*. When users provision a cluster with replicas in TigerGraph Cloud, a load balancer will be automatically attached to the cluster.
* *Multi-AZ deployment*. When a user provisions an HA cluster, the replicas of the cluster will automatically be provisioned on different availability zones. This feature is supported on AWS and GCP.
* *Free-tier clusters on GCP*. We now offer the option to create a free-tier cluster on GCP in addition to AWS.

== May 2021 Updates

Release Date: May 17, 2021

=== New features

* ✅Support TigerGraph V3.1.1 for New Clusters (Single Server)

== March 2021 Updates

Release Date: March 17, 2021

=== New features

* ✅Support GCP (Google Cloud Platform) as one of the Cloud Platforms

== March 2021 Updates

Release Date: March 9, 2021

=== New features

* ✅Add Azure Central India and South India Regions to Cloud Platforms

== Feb 2021 Updates

Release Date: February 17, 2021

=== New features

* ✅Add Cloud Portal Self Guided Tour
* ✅Support Minimum Disk Size Check During New Cluster Provisioning Process

== Dec 2020 Updates

Release Date:  December 16, 2020

=== New features

* ✅Pricing Change
** Instance Pricing Change
** Backup Pricing Change
** Replica Pricing Change
** New Data Transfer Cost (First 50GB free for 2 hour+ uptime per month )
* ​✅Support TigerGraph V3.0.6 for New Clusters
* ​​✅Support TigerGraph v2.6.4 for New Clusters
* ✅Support replication factor of 3 for TigerGraph V3.0.6 clusters
* ✅New TigerGraph Cloud Instance Type TG.C4.M16 available from AWS
* ✅SOC2 Type 2 report available to request
* ✅5 New TigerGraph Starter Kits
** Graph Convolutional Networks (V3.0.6)
** Healthcare Graph (Drug Interaction/FAERS) (V3.0.6)
** Social Network Analysis (V2.6.4 and V3.0.6)
** Enterprise Knowledge Graph (Corporate Data) (V2.6.4 and V3.0.6)
** Enterprise Knowledge Graph (Crunchbase) (V2.6.4 and V3.0.6)

== September 2020 Updates

Release Date:  September 29, 2020

=== Patch

* ✅Patch TigerGraph V3.0.5 with GSQL Bug Fixes for New Clusters

== September 2020 Updates

Release Date:  September 17, 2020

=== New features

* ✅Support TigerGraph V3.0.5 for New Clusters
* ✅Support TigerGraph v2.6.3 for New Clusters
* ✅Allow Users to choose  v2.6.3 or V3.0.5 at New Cluster Provisioning

== July 2020 Updates

Release Date:  July 10, 2020

=== New features

* ✅Support Microsoft Azure as one of the Cloud Platforms

== April 2020 Updates

Release Date:  April 27, 2020

=== New features

* ✅Advanced Developer Tool: GSQL Web Shell for Non-Free Tiers
* ✅TigerGraph Database Version Upgrades to TigerGraph 2.6 For New Instances
* ✅Starter Kit Categorization at Cluster Provisioning
* ✅6 New TigerGraph Starter Kits
** COVID-19 Starter Kit
** In-Database Machine Learning Recommendation
** Low-Rank Approximation Machine Learning
** Graph Algorithms
*** Shortest Path
*** Centrality
*** Community Detection

== TigerGraph Cloud V2.0

Release Date: January 08, 2020

=== New features

* ✅New product name: "TigerGraph Distributed Cloud"
* ✅New URL: tgcloud.io
* ✅Option to provision a TigerGraph Distributed Cluster
* ✅Option to provision a Highly Available TigerGraph Cluster
* ✅Added Steps in Cloud Portal Provision Workflow
* ✅New TigerGraph Starter Kits

== TigerGraph Cloud V1.0

Release Date: September 25, 2019

Deprecation Date: March 31, 2020

=== New features

* ✅Single Server Enterprise Edition
* ✅Self-service Signup and Registration at tgcloud.us
* ✅Free Credits for 1st Time Sign Up
* ✅Available in 8 Tiers of Instances (Free Tier Included) and 6 Global Regions
* ✅Flexible Billing and Pay As You Go Pricing
* ✅Secure and Isolated Network (VPC) for Each TigerGraph Cloud Account
* ✅Fast Data Loading through S3 and Local Files
* ✅13 TigerGraph Starter Kits with Sample Datasets and Queries
* ✅Start/Stop/Terminate TigerGraph Clusters On Demand through Cloud Portal
* ✅Built-in Backup and Restore through TigerGraph Admin Portal
* ✅Rich Metrics from System Monitoring Panel on Cloud Portal
* ✅Convenient Application Development Through RESTful Endpoints
