= Resource Manager
:experimental:

In TigerGraph Cloud 4.0, the concepts of workgroup, workspace, and database are used to organize and manage projects and data within the platform.

By utilizing xref:cloudBeta:resource-manager:workgroup.adoc[workgroups], xref:cloudBeta:resource-manager:workspaces/workspace.adoc[workspaces and databases], TigerGraph Cloud 4.0 provides a flexible and scalable environment for managing projects, allocating compute resources, and working with graph data effectively.

////
[CAUTION]
====
TigerGraph Cloud 4.0 is still in beta release and the documentation is in progress.
====

[IMPORTANT]
====
TigerGraph Cloud 4.0 beta is  for personal or R&D use and not for production use.

It is not covered by our xref:cloudBeta:resources:terms_conditions.adoc[].
====
////

== xref:resource-manager:workgroup.adoc[]

Here you can learn xref:how2-create-a-workgroup.adoc[] the first step before creating a xref:workspaces/workspace.adoc[Workspace]
and learning xref:how2-workgroup-access.adoc[].


== xref:cloudBeta:resource-manager:workspaces/workspace.adoc[Workspace and Database Overview]
Here you can learn xref:workspaces/how2-create-a-workspace.adoc[] and unlock its many features.

Such as:

=== xref:cloudBeta:resource-manager:workspaces/advanced-settings/advanced-settings.adoc[]
---

=== xref:workspaces/writeread_readonly.adoc[]
---

=== xref:workspaces/workspace-size.adoc[]
---


=== xref:expansion_shrink.adoc[]
---
Learn how to adjust the capacity of  your workspaces as your data grows or changes.

=== xref:backup-and-restore.adoc[]
---
Learn how to create backup points and restore your workspace to a specific point in time.

=== xref:resource-manager:connect_via_api.adoc[]
---
Learn how to connect to your graph database using REST APIs.

=== xref:resource-manager:monitor_workspaces.adoc[]
---
Learn how TigerGraph Cloud 4.0 offers comprehensive monitoring capabilities that allow you to track the status and resource usage of your workspaces.




