= Workgroups and Workspaces
:experimental:

In TigerGraph Savanna, the concepts of workgroup, workspace, and database are used to organize and manage projects and data within the platform.
By utilizing xref:savanna:workgroup-workspace:workgroups/workgroup.adoc[workgroups], xref:savanna:workgroup-workspace:workspaces/workspace.adoc[workspaces and databases], TigerGraph Savanna provides a flexible and scalable environment for managing projects, allocating compute resources, and working with graph data effectively.

== xref:savanna:workgroup-workspace:workgroups/workgroup.adoc[]

Learn xref:savanna:workgroup-workspace:workgroups/how2-create-a-workgroup.adoc[] the first step before creating a xref:savanna:workgroup-workspace:workspaces/workspace.adoc[Workspace]
and learning xref:savanna:workgroup-workspace:workgroups/how2-workgroup-access.adoc[].


== xref:savanna:workgroup-workspace:workspaces/workspace.adoc[Workspace and Database Overview]
Learn xref:savanna:workgroup-workspace:workspaces/how2-create-a-workspace.adoc[] and unlock its many features.

Such as:

* xref:savanna:workgroup-workspace:workspaces/settings.adoc[]
-
Learn how advanced settings in workspace allow users to customize and fine tune various aspects of their workspace configuration.

* xref:savanna:workgroup-workspace:workspaces/readwrite-readonly.adoc[]
-
Learn how Read-Write (RW) and Read-Only (RO) Workspaces will connect to a database.

* xref:savanna:workgroup-workspace:workspaces/workspace-size.adoc[]
-
Learn how to specify the size based on your data and performance requirements.

* xref:savanna:workgroup-workspace:workspaces/expansion-shrink.adoc[]
-
Learn how to adjust the capacity of  your workspaces as your data grows or changes.

* xref:savanna:workgroup-workspace:workgroups/backup-and-restore.adoc[]
-
Learn how to create backup points and restore your workspace to a specific point in time.

* xref:savanna:workgroup-workspace:workspaces/connect-via-api.adoc[]
-
Learn how to connect to your graph database using REST APIs.

* xref:savanna:workgroup-workspace:workgroups/monitor-workspaces.adoc[]
-
Learn how TigerGraph Savanna offers comprehensive monitoring capabilities that allow you to track the status and resource usage of your workspaces.

== Next Steps

Next, learn how to xref:savanna:graph-development:load-data/index.adoc[Load Data] into TigerGraph Savanna.

Or return to the xref:savanna:overview:index.adoc[Overview] page for a different topic.



