= Managing Users in an Organization
:experimental:

When you set up a TigerGraph Cloud account, you are granted the privileges of an Organization Admin for your company.

TigerGraph Cloud allows an Organization Admin to manage multiple users in your organization and control their access to various solutions.

This page will explain the user access controls. For help with setting up solutions, visit xref:create-a-solution.adoc[].

== Manage users in an organization
The account that creates an organization is automatically given the privileges of an Organization Admin.
Upon login, you have the opportunity to add additional users to your organization with different roles and privileges.

=== Organization roles and privileges

The privileges granted to the various roles are as follows:

|====
|Action | Organization Member | Organization Solution Admin |Organization Admin
|Can add and remove new members | No 🚫 | No 🚫|  Yes✅
|Can view organization billing information | No 🚫 |No 🚫|Yes✅
|Can create new solutions |No 🚫|Yes ✅|Yes✅
|Can view solution activities |No 🚫|Yes ✅|Yes✅
|Can shut down/modify an existing solution |No 🚫|Yes ✅|Yes✅
|Can view solution data |Only if assigned to the solution |Yes✅|Yes✅
|Can access GraphStudio| Only if assigned to the solution |Only if assigned to the solution |Only if assigned to the solution
|====

=== Access Management

On the User Access Management page, you can check the invitation status of each user who has been sent an invitation and also invite new users.

Click on the three-dot menu btn:[•••] to modify a user's role or delete the account. Deleting the account removes the user from all solutions in the organization.

Click btn:[Invite Users] in the upper-right corner of the page to send out more email invitations to new users and place them in various roles.

You can also group your users into a team by clicking btn:[Create Team] in the upper-right corner. Teams are helpful for granting and revoking access to certain solutions for large numbers of users.

=== Solution Management

On the *My Solutions* page, click the third button in the Actions row for each solution to enter the *Solution Access Management* page. From there, you can manage the users who have access to the solution and their roles.