= TigerGraph Cloud
:experimental:
:page-aliases: getting-started.adoc

TigerGraph Cloud is a fully-managed cloud database built on the same TigerGraph Enterprise Server engine that delivers the fastest and most scalable graph database.
TigerGraph Cloud handles all the complexity of deploying and managing your deployments on the cloud service provider of your choice (AWS, Azure, and GCP).

TigerGraph Cloud is completely integrated with the full TigerGraph Suite.
Everything including Admin Portal, GraphStudio, Insights, and more is available with a TigerGraph Cloud instance.

== Get started with TigerGraph Cloud

Click btn:[Sign Up] on the https://tgcloud.io/[TigerGraph Cloud landing page].

When you register for a new TigerGraph Cloud account, you create an Organization Account to which you can later invite other users.

Create a new account with a company name, personal name, email address, and password of your choice.

After completing the signup page, you will get a link to verify your email address.
Click the link in your email to verify, then log in using your username and password.

If you have already verified your email address, you can still create a new organization on the Sign Up page.
The system recognizes a verified email address on the registration page and allows you to create a new organization with the same credentials.

[NOTE]
====
TigerGraph recommends enterprise customers use a shared mailbox to set up an organization account.
TigerGraph Cloud sends important email notifications to this address, including for:

* Billing and credits
* Cluster behavior
* New cloud products
====

=== Log in

Click btn:[Log In] on the https://tgcloud.io/[TigerGraph Cloud landing page].

When you log in, you must first provide an organization name before entering your username and password.
If you were invited by a member of your organization and you do not know the name used for the organization account, contact your organization's administrator.

Once logged in, you can create clusters and add more users to your organization.

* xref:solutions:create-a-solution.adoc[]
* xref:security:manage-org-users.adoc[]

== Manage TigerGraph Cloud clusters

* xref:gui:admin-portal:management/user-management.adoc[Security and user management]
* xref:backup-and-restore:index.adoc[Backup and restore]

== Billing

* xref:billing:manage-payment-methods.adoc[Manage payment methods]
* xref:billing:subscriptions.adoc[Cloud Marketplace subscriptions]

== FAQs

See the xref:support:faqs.adoc[TigerGraph Cloud FAQs] for answers to common questions.

== Comparison with TigerGraph Enterprise Server

Most of the documentation for TigerGraph Enterprise Server also applies to TigerGraph Cloud.
However, since TigerGraph Cloud does not have a command-line interface on the OS level, command-line features are not supported in the same way.
In many cases, there is a GUI-based method for the same feature.
For advanced OS-level commands, submit a support ticket for more information.


|===
| Topic | TigerGraph Enterprise Server | TigerGraph Cloud

| GSQL Graph Algorithm Library
| Yes
| Yes

| Release Notes
| Yes
| TigerGraph Cloud provides database versions kept up to date with TigerGraph Server releases.

| GSQL 101
| Yes
| Basic concepts still apply, most CREATE, INSTALL, LOAD, and RUN commands are replaced with the GraphStudio GUI-based approach.

| GSQL 102 Pattern Matching
| Yes
| The same patterns can be used in queries.

| MultiGraph Overview
| Yes
| Yes

| Hardware and Software Requirements
| Yes
| N/A

| Installation and Configuration
| Yes
| N/A. There are a few simple steps to install a Starter Kit.  See the TigerGraph Cloud FAQs.

| User Access Management
| Yes
| Yes

| Data Encryption
| Yes
| N/A. TigerGraph Cloud is setup already for encrypted data at rest and at motion.

| System Management
| Yes
| The Cloud Admin Portal is enhanced over the TigerGraph Server Admin Portal.  Backup and Restore is done through the Cloud Admin Portal.

| GraphStudio UI Guide
| Yes
| Yes

| GSQL Demo Examples
| Yes
| Yes

| GSQL Language Reference, Part 1 Data Definition and Loading
| Yes
| Yes. GSQL Web Shell (Paid Tiers) supports Data Definition and Loading. Data files can be imported into the filesystem through GraphStudio, or submit support request to import into the filesystem. In addition, the operations can be performed through the GraphStudio user interface.

| GSQL Language Reference, Part 2 Querying
| Yes
| Yes

| RESTPP API User Guide
| Yes
| Yes. Note the URL assigned to your cluster.

| Transaction Processing and ACID Support
| Yes
| Yes

| Data Loader User Guides
| Yes
| S3 Loader can be used through the GraphStudio interface. In addition, S3 Loader and Kafka Loader can be used in GSQL Web Shell (Paid Tiers).
|===
