= AWS PrivateLink
:experimental:
:description: Setting up PrivateLink on Amazon Web Services

== AWS customer instructions
DNS Hostnames must be set to enabled in your VPC to use the TigerGraph private DNS.

See instructions at this link: link:https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#vpc-dns-updating[View and update DNS attributes for your VPC]

=== Create VPC endpoint via AWS CLI

You need the following IDs to generate the CLI command

* Customer VPC ID
* Customer Subnet ID(s)
* Customer AWS Account ARN, IAM Role ARN, or IAM User ARN (If we want automatic approval)

.Sample command-line request to create VPC endpoint
[source.wrap]
----
aws ec2 create-vpc-endpoint
--vpc-id vpc-ec43eb89
--vpc-endpoint-type Interface
--service-name com.amazonaws.vpce.us-east-1.vpce-svc-0a85faeb9b6f57977
--subnet-id subnet-1 subnet-2
--security-group-id sg-1a2b3
----

If no security group is specified, the default security group for your VPC will be selected.
In order to communicate with your TG Solution via AWS Private link, inbound and outbound connections to our service on ports 443, 14240, and 9000 must be allowed.

=== Create VPC Endpoint via Console
AWS has detailed step-by-step instructions here: link:https://docs.aws.amazon.com/vpc/latest/privatelink/vpce-interface.html#create-interface-endpoint[Access an AWS service using an interface VPC endpoint]


