= GCP Private Service Connect
:experimental:
:description: Setting up Private Service Connect on Google Cloud Platform (GCP)

== GCP General Workflow
[User] Customer select “Private“ or “Public and Private“ option when provisioning new solution.

[tgcloud] A “Private Service Connect”(GCP) will be provisioned, a “Service Attachment“ will be provided to customer.

[User] Customer create “Private Service Connect endpoint”(GCP) in their GCP account using the service name above.

[User] Customer confirm on tgcloud portal that their Endpoint has been created

[tgcloud] Approve the endpoint connection

=== GCP Customer Instructions
==== Private Service Connect Endpoint
Verify that a dedicated subnet with Purpose “None“ exists to contain the Private Service Connect endpoint.

Create static IP address for the Private Service Connect endpoint in subnet from step 1.

Navigate to the GCP portal. Search for Private Service Connect and click Connect Endpoint.

In the Target choose Published service, fill Target Service with service name TigerGraph provided. Choose in Subnetwork and IP address services from steps 1 and 2. Click Add Endpoint button.

Return to the Private service connect section and allow a few minutes to wait. On approval, the  Endpoint displays a Status value of Accepted.

==== Private DNS
Create a Private DNS Zone named privatelink.i.tgcloud.io

In the created DNS zone add a DNS A record named {solutiondomain}.privatelink.i  (example: abcdefg.privatelink.i), the value is the private static IP address for Private Service Connect.