= Read/Write and Read Only Workspaces

Read-Write and Read-Only Workspaces will connect to the same database allowing users to dynamically control OLTP (define) and OLAP (define) workloads for complete isolation of analytical and transactional traffic.

== Read-Write (RW) Workspace

Read-Write (RW) workspaces allow read and write operations on the graph data.
They are typically used for loading data, data updates, and running queries that modify the graph structure or properties.

//[Placeholder for create a new database]

//=== Create a Read-Write workspace

== Read-Only (RO) Workspace

Read-Only (RO) workspaces are optimized for read-intensive operations.
They are used for executing queries and analytics on the graph data without modifying it.
Read-only workspaces provide improved performance and scalability for read operations.

//[Placeholder for attach to an existing database]

[NOTE]
====
Current RO workspace requires manual sync up with the RW workspace to catch up with the latest change.

In RO workspace, the following operations are forbidden:

1. run write queries
2. create/drop graph
3. update schema (add/update/drop), create/drop/run schema change job
4. update data (insert/update/delete)
5. backup/restore
6. export/import
7. drop all
8. clear graph store
9. rebuild
10. gadmin/gsql reset
11. create/delete/run loading job
12. create/update datasource 
13. create/delete/pause/restart/resume connector
====

=== Update Read-Only(RO) Workspace

Once a Read-Only (RO) workspace is created, it also creates a snapshot of the data.
You can manually sync up the data with Read-Write(RW) workspace when needed.

//[Placeholder for update read-only workspace]

[NOTE]
Updating a Read-Only (RO) workspace is an offline operation.

If there are any other operations in progress on the RO workspace, they are likely to be affected during the update process.

[TIP]
====
It is recommended to schedule the update during a time when minimal or no operations are expected on the RO workspace to avoid any potential disruptions.
====

== Next Steps

Next, about xref:workspaces/workspace-size.adoc[Workspace Sizes] or learn how to xref:cloudBeta:resource-manager:expansion_shrink.adoc[Expand and Shrink] a workspace.

Return to the xref:cloudBeta:resource-manager:index.adoc[] page or xref:cloudBeta:overview:index.adoc[Overview] page for a different topic.


