= Read/Write and Read Only Workspaces

Read-Write and Read-Only Workspaces will connect to the same database allowing users to dynamically control OLTP (define) and OLAP (define) workloads for complete isolation of analytical and transactional traffic.

== Read-Write (RW) Workspace

Read-Write (RW) workspaces allow read and write operations on the graph data.
They are typically used for loading data, data updates, and running queries that modify the graph structure or properties.

//[Placeholder for create a new database]

//=== Create a Read-Write workspace

== Read-Only (RO) Workspace

Read-Only (RO) workspaces are optimized for read-intensive operations.
They are used for executing queries and analytics on the graph data without modifying it.
Read-only workspaces provide improved performance and scalability for read operations.

//[Placeholder for attach to an existing database]

[NOTE]
====
Current Read-Only (RO) workspace requires manual sync up with the RW workspace to catch up with the latest change.

In a Read-Only (RO) workspace within TigerGraph Cloud, the following operations are strictly prohibited:

[.prohibited]
.Database Operations
- Running "gsql --reset" command.
- Clearing the graph store.
- Executing the DROP ALL command.

[.prohibited]
.Schema Management
- Updating schemas, including adding, updating, or dropping schema elements.
- Creating, dropping, or running schema change jobs.

[.prohibited]
.Graph Management
- Creating or dropping graphs.
- Exporting or importing database data.

[.prohibited]
.Data Modification
- Running any queries that modify the database data.
- Inserting, updating, or deleting data.
- Committing the data(such as new vertices or edges) in memory to disk. for example: rebuildnow operation

[.prohibited]
.Loading Jobs
- Creating, deleting, or running loading jobs.
- Creating, deleting, pausing, restarting, or resuming connectors.
- Creating or updating data sources.

[.prohibited]
.Backup and Restore
- Performing backup or restore operations.

====

=== Update Read-Only(RO) Workspace

Once a Read-Only (RO) workspace is created, it also creates a snapshot of the data.
You can manually sync up the data with Read-Write(RW) workspace when needed.

//[Placeholder for update read-only workspace]

[NOTE]
Updating a Read-Only (RO) workspace is an offline operation.

If there are any other operations in progress on the RO workspace, they are likely to be affected during the update process.

[TIP]
====
It is recommended to schedule the update during a time when minimal or no operations are expected on the RO workspace to avoid any potential disruptions.
====

== Next Steps

Next, about xref:workspaces/workspace-size.adoc[Workspace Sizes] or learn how to xref:cloudBeta:resource-manager:expansion_shrink.adoc[Expand and Shrink] a workspace.

Return to the xref:cloudBeta:resource-manager:index.adoc[] page or xref:cloudBeta:overview:index.adoc[Overview] page for a different topic.


