= Sizing and Scaling

TigerGraph Cloud offers different choices when it comes to instance types and disk sizes. This document helps you find the right instance type and disk size for your workload.

== Choose the right instance type

Larger graphs require more RAM. Higher performance calls for both more CPUs and more RAM.

Our https://www.tigergraph.com/tigergraph-cloud-pricing/[pricing table] gives initial recommendations for which instance type to start with if you know how much data you will be loading into the graph. We call the input data your *raw data*. TigerGraph reorganizes your data into a graph, encoding and compressing it. We assume that your stored graph will be about 70% of the size of your raw data. This is a conservative estimate; it's often smaller.

You also need RAM for your graph querying and computation. Workloads vary considerably. In the pricing table, we recommend that your total RAM be about 1.5 times the maximum amount of raw data you think you will load.

== Choose the right disk size

Disk storage refers to the root disk attached to your instance that holds the following files:

* OS installation files
* TigerGraph database installation files
* TigerGraph Graph storage
* Other data files uploaded to the instance
* Any output files generated by querying the database
* Logs generated while running TigerGraph

When you choosing the size of the disk, consider the size of the data for all the above installations and files.

To ensure adequate disk storage, TigerGraph Cloud mandates that any disk size of a solution must be *at least 3 times* the size of its instance's RAM. For example, if your solution instance has 64 GB of RAM, then the disk size must be higher than 192 GB.
