= Manage your TigerGraph Cloud User Account
:experimental:

== Creating an account

Only an Organization Admin can create a new user account for someone else to use. Organization Members and Organization Cluster Admins cannot create their own accounts; they need to be invited via email after their accounts are created for them.

See xref:manage-org-users.adoc#_invite_new_users[Invite new users] for more detailed instructions.

== Account name

Your user account is displayed in the order [First Name] [Last Name] in the list of users in the organization account.

Changing your display name is not currently supported by TigerGraph Cloud.
To change your name, an Organization Admin needs to remove your account and send a new invitation for you to make a new account.

== Account permissions

Search for your own name under the *Users* tab to see what role you have been given in the organization.
If you believe you have been given the wrong organization role in error, contact an Organization Admin for them to change your role.

See xref:manage-org-users.adoc#_organization_roles_and_privileges[Organization roles and privileges] for detailed information on the privileges available to each organization role.

== Reset your TigerGraph Cloud user account password

. Go to the https://tgcloud.io[TigerGraph Cloud main page].
. Click the *Login* link next to "Have an account?"
. Enter your organization name. If you don't remember your organization name, contact your administrator.
. Click *Forgot password?*
. Enter your email address. If you signed up using an identity provider such as Google or LinkedIn, use the email address associated with that account. Click btn:[Continue].
. Look for an email in your inbox titled *Reset your password*. Click on the link in the email.
. Enter your new password.
