= User Management
:page-aliases: readme.adoc, README.adoc

This section describes the way user accounts work at different access levels in TigerGraph Cloud.

== TigerGraph Cloud user account

Your TigerGraph Cloud user account serves as your credential on the platform level.
Depending on your role, you have various levels of access to solutions, billing information and organization user information.

See xref:manage-cloud-account.adoc[] for more information about making changes to your account.

== TigerGraph user access levels

On the individual solution level, the same xref:gui:admin-portal:management/user-management.adoc[role-based access control] used by the on-premises version of TigerGraph also applies to TigerGraph Cloud.
Each solution or solution cluster can have many TigerGraph Cloud users and each user can have different roles for each graph with different privileges.

For more information on how to manage users and roles in Admin Portal, see xref:gui:admin-portal:management/user-management.adoc[].

[NOTE]
User management was redesigned with the release of TigerGraph v3.6.0 in July 2022. Clusters created before then are only visible to Organization Admins and Cluster Admins.
These legacy clusters exist entirely outside of the User Management system and can still be accessed by ordinary users with the URL.

== Preconfigured security features

=== Encryption-at-rest

All data loaded into TigerGraph Cloud, including data in disk storage and backups, are automatically encrypted-at-rest using the cloud provider's native encryption protocol with platform-managed keys.

=== Transport Layer Security (TLS)

TigerGraph Cloud uses TLS to encrypt connections to your graph databases.

=== RESTPP Authentication

By default, all TigerGraph Cloud solutions have RESTPP authentication turned on. To make requests to the RESTPP server, you must generate a secret in the Admin Portal and use that secret to generate an authentication token.
