= Service Limits

By default, TigerGraph Cloud limits how many instances and how many vCPUs a single account can provision. These limits can be waived by request if you have a valid credit card on your account. To waive a service limit, please contact link:mailto:sales@tigergraph.com[sales@tigergraph.com].

The table below outlines the service limits for accounts with and without a valid credit card.

[width="100%",cols="<34%,<33%,<33%",options="header",]
|===
|Service |*Accounts with a valid credit card* |*Accounts without a valid
credit card*
|*Free Tier Solution* |1 |1

|*Total Instances* |20 |2

|*Total vCPUs* |160 |16

a|
*Cluster Size*

(replication factor * partition factor)

|10 instances |1

|*Replication Factor* |3 |1

|*Backup and Restore* |Yes |No

|*GSQL Web Shell Access* |Yes |No
|===

== Free tier solution limits

Each registered account is allowed one solution from the Free Tier. Free Tier instances do not include backups or support.

If no user activity is detected for more than one hour, TigerGraph may automatically stop a Free Tier instance. Users can manually restart the free tier instances from their cloud portal. After 7 days of inactivity, TigerGraph may terminate the inactive free tier instances.
